### ISSUE TITLE
Add support for custon openshift options.

### ISSUE THREAD

**Issue by pierreozoux** [aws-quickstart/quickstart-redhat-openshift#156]

**Comment by jaymccon** [comment]
This is something we've had in the past, in the form of a parameter that got pushed into the ansible config. It turned out to be very difficult to maintain. There are many possible options, some conflicting with options that are prescriptively set in the quickstart, and some that can conflict with each other. 

My recommendation for those wishing to customize the openshift-ansible config is to fork the repo and add required parameters [here](https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/master/scripts/predefined_openshift_vars.txt).

If there are specific options that are generally useful we can consider adding those config options individually.
